#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecta.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Proyecta")]
	public partial class ModeloDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertInstitucion(Institucion instance);
    partial void UpdateInstitucion(Institucion instance);
    partial void DeleteInstitucion(Institucion instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertPersona(Persona instance);
    partial void UpdatePersona(Persona instance);
    partial void DeletePersona(Persona instance);
    partial void InsertProyecto(Proyecto instance);
    partial void UpdateProyecto(Proyecto instance);
    partial void DeleteProyecto(Proyecto instance);
    partial void InsertProyecto_Imagene(Proyecto_Imagene instance);
    partial void UpdateProyecto_Imagene(Proyecto_Imagene instance);
    partial void DeleteProyecto_Imagene(Proyecto_Imagene instance);
    partial void InsertProyecto_Persona(Proyecto_Persona instance);
    partial void UpdateProyecto_Persona(Proyecto_Persona instance);
    partial void DeleteProyecto_Persona(Proyecto_Persona instance);
    partial void InsertRetroaliimentacion_Proyecto(Retroaliimentacion_Proyecto instance);
    partial void UpdateRetroaliimentacion_Proyecto(Retroaliimentacion_Proyecto instance);
    partial void DeleteRetroaliimentacion_Proyecto(Retroaliimentacion_Proyecto instance);
    #endregion
		
		public ModeloDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ProyectaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Institucion> Institucions
		{
			get
			{
				return this.GetTable<Institucion>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Persona> Personas
		{
			get
			{
				return this.GetTable<Persona>();
			}
		}
		
		public System.Data.Linq.Table<Proyecto> Proyectos
		{
			get
			{
				return this.GetTable<Proyecto>();
			}
		}
		
		public System.Data.Linq.Table<Proyecto_Imagene> Proyecto_Imagenes
		{
			get
			{
				return this.GetTable<Proyecto_Imagene>();
			}
		}
		
		public System.Data.Linq.Table<Proyecto_Persona> Proyecto_Personas
		{
			get
			{
				return this.GetTable<Proyecto_Persona>();
			}
		}
		
		public System.Data.Linq.Table<Retroaliimentacion_Proyecto> Retroaliimentacion_Proyectos
		{
			get
			{
				return this.GetTable<Retroaliimentacion_Proyecto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Institucion")]
	public partial class Institucion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _Id_Persona;
		
		private string _Nombre_Institucion;
		
		private string _Cedula_Representante;
		
		private string _UrlLogo;
		
		private EntityRef<Persona> _Persona;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnId_PersonaChanging(System.Guid value);
    partial void OnId_PersonaChanged();
    partial void OnNombre_InstitucionChanging(string value);
    partial void OnNombre_InstitucionChanged();
    partial void OnCedula_RepresentanteChanging(string value);
    partial void OnCedula_RepresentanteChanged();
    partial void OnUrlLogoChanging(string value);
    partial void OnUrlLogoChanged();
    #endregion
		
		public Institucion()
		{
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Persona", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Id_Persona
		{
			get
			{
				return this._Id_Persona;
			}
			set
			{
				if ((this._Id_Persona != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_PersonaChanging(value);
					this.SendPropertyChanging();
					this._Id_Persona = value;
					this.SendPropertyChanged("Id_Persona");
					this.OnId_PersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Institucion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre_Institucion
		{
			get
			{
				return this._Nombre_Institucion;
			}
			set
			{
				if ((this._Nombre_Institucion != value))
				{
					this.OnNombre_InstitucionChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Institucion = value;
					this.SendPropertyChanged("Nombre_Institucion");
					this.OnNombre_InstitucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula_Representante", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Cedula_Representante
		{
			get
			{
				return this._Cedula_Representante;
			}
			set
			{
				if ((this._Cedula_Representante != value))
				{
					this.OnCedula_RepresentanteChanging(value);
					this.SendPropertyChanging();
					this._Cedula_Representante = value;
					this.SendPropertyChanged("Cedula_Representante");
					this.OnCedula_RepresentanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlLogo", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string UrlLogo
		{
			get
			{
				return this._UrlLogo;
			}
			set
			{
				if ((this._UrlLogo != value))
				{
					this.OnUrlLogoChanging(value);
					this.SendPropertyChanging();
					this._UrlLogo = value;
					this.SendPropertyChanged("UrlLogo");
					this.OnUrlLogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Institucion", Storage="_Persona", ThisKey="Id_Persona", OtherKey="Id", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Institucions.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Institucions.Add(this);
						this._Id_Persona = value.Id;
					}
					else
					{
						this._Id_Persona = default(System.Guid);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _Id_Persona;
		
		private string _Password;
		
		private string _NombreUsuario;
		
		private string _Correo;
		
		private EntityRef<Persona> _Persona;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnId_PersonaChanging(System.Guid value);
    partial void OnId_PersonaChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnNombreUsuarioChanging(string value);
    partial void OnNombreUsuarioChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    #endregion
		
		public Usuario()
		{
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Persona", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Id_Persona
		{
			get
			{
				return this._Id_Persona;
			}
			set
			{
				if ((this._Id_Persona != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_PersonaChanging(value);
					this.SendPropertyChanging();
					this._Id_Persona = value;
					this.SendPropertyChanged("Id_Persona");
					this.OnId_PersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this.OnNombreUsuarioChanging(value);
					this.SendPropertyChanging();
					this._NombreUsuario = value;
					this.SendPropertyChanged("NombreUsuario");
					this.OnNombreUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Usuario", Storage="_Persona", ThisKey="Id_Persona", OtherKey="Id", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._Id_Persona = value.Id;
					}
					else
					{
						this._Id_Persona = default(System.Guid);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persona")]
	public partial class Persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Cedula;
		
		private string _Nombre;
		
		private string _Apellido1;
		
		private string _Apellido2;
		
		private string _urlFoto;
		
		private char _Genero;
		
		private EntitySet<Institucion> _Institucions;
		
		private EntitySet<Usuario> _Usuarios;
		
		private EntitySet<Proyecto_Persona> _Proyecto_Personas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnCedulaChanging(string value);
    partial void OnCedulaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellido1Changing(string value);
    partial void OnApellido1Changed();
    partial void OnApellido2Changing(string value);
    partial void OnApellido2Changed();
    partial void OnurlFotoChanging(string value);
    partial void OnurlFotoChanged();
    partial void OnGeneroChanging(char value);
    partial void OnGeneroChanged();
    #endregion
		
		public Persona()
		{
			this._Institucions = new EntitySet<Institucion>(new Action<Institucion>(this.attach_Institucions), new Action<Institucion>(this.detach_Institucions));
			this._Usuarios = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuarios), new Action<Usuario>(this.detach_Usuarios));
			this._Proyecto_Personas = new EntitySet<Proyecto_Persona>(new Action<Proyecto_Persona>(this.attach_Proyecto_Personas), new Action<Proyecto_Persona>(this.detach_Proyecto_Personas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido1", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Apellido1
		{
			get
			{
				return this._Apellido1;
			}
			set
			{
				if ((this._Apellido1 != value))
				{
					this.OnApellido1Changing(value);
					this.SendPropertyChanging();
					this._Apellido1 = value;
					this.SendPropertyChanged("Apellido1");
					this.OnApellido1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido2", DbType="VarChar(20)")]
		public string Apellido2
		{
			get
			{
				return this._Apellido2;
			}
			set
			{
				if ((this._Apellido2 != value))
				{
					this.OnApellido2Changing(value);
					this.SendPropertyChanging();
					this._Apellido2 = value;
					this.SendPropertyChanged("Apellido2");
					this.OnApellido2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlFoto", DbType="VarChar(256)")]
		public string urlFoto
		{
			get
			{
				return this._urlFoto;
			}
			set
			{
				if ((this._urlFoto != value))
				{
					this.OnurlFotoChanging(value);
					this.SendPropertyChanging();
					this._urlFoto = value;
					this.SendPropertyChanged("urlFoto");
					this.OnurlFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="Char(1) NOT NULL")]
		public char Genero
		{
			get
			{
				return this._Genero;
			}
			set
			{
				if ((this._Genero != value))
				{
					this.OnGeneroChanging(value);
					this.SendPropertyChanging();
					this._Genero = value;
					this.SendPropertyChanged("Genero");
					this.OnGeneroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Institucion", Storage="_Institucions", ThisKey="Id", OtherKey="Id_Persona")]
		public EntitySet<Institucion> Institucions
		{
			get
			{
				return this._Institucions;
			}
			set
			{
				this._Institucions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Usuario", Storage="_Usuarios", ThisKey="Id", OtherKey="Id_Persona")]
		public EntitySet<Usuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Proyecto_Persona", Storage="_Proyecto_Personas", ThisKey="Id", OtherKey="IdPersona")]
		public EntitySet<Proyecto_Persona> Proyecto_Personas
		{
			get
			{
				return this._Proyecto_Personas;
			}
			set
			{
				this._Proyecto_Personas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Institucions(Institucion entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Institucions(Institucion entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Proyecto_Personas(Proyecto_Persona entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Proyecto_Personas(Proyecto_Persona entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proyecto")]
	public partial class Proyecto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Cedula_Proponiente;
		
		private string _Propuesta;
		
		private string _Recursos;
		
		private string _Provincia;
		
		private string _Canton;
		
		private System.Nullable<short> _PromedioEvaluacion;
		
		private System.Nullable<int> _CantidadEvaluacionesUsarios;
		
		private string _Nombre;
		
		private System.DateTime _FechaCreacion;
		
		private System.Nullable<System.DateTime> _FechaInicio;
		
		private System.Nullable<System.DateTime> _FechaFinal;
		
		private char _Estado;
		
		private string _Categoria;
		
		private string _urlImagen;
		
		private EntitySet<Proyecto_Imagene> _Proyecto_Imagenes;
		
		private EntitySet<Proyecto_Persona> _Proyecto_Personas;
		
		private EntitySet<Retroaliimentacion_Proyecto> _Retroaliimentacion_Proyectos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnCedula_ProponienteChanging(string value);
    partial void OnCedula_ProponienteChanged();
    partial void OnPropuestaChanging(string value);
    partial void OnPropuestaChanged();
    partial void OnRecursosChanging(string value);
    partial void OnRecursosChanged();
    partial void OnProvinciaChanging(string value);
    partial void OnProvinciaChanged();
    partial void OnCantonChanging(string value);
    partial void OnCantonChanged();
    partial void OnPromedioEvaluacionChanging(System.Nullable<short> value);
    partial void OnPromedioEvaluacionChanged();
    partial void OnCantidadEvaluacionesUsariosChanging(System.Nullable<int> value);
    partial void OnCantidadEvaluacionesUsariosChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnFechaInicioChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaInicioChanged();
    partial void OnFechaFinalChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaFinalChanged();
    partial void OnEstadoChanging(char value);
    partial void OnEstadoChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnurlImagenChanging(string value);
    partial void OnurlImagenChanged();
    #endregion
		
		public Proyecto()
		{
			this._Proyecto_Imagenes = new EntitySet<Proyecto_Imagene>(new Action<Proyecto_Imagene>(this.attach_Proyecto_Imagenes), new Action<Proyecto_Imagene>(this.detach_Proyecto_Imagenes));
			this._Proyecto_Personas = new EntitySet<Proyecto_Persona>(new Action<Proyecto_Persona>(this.attach_Proyecto_Personas), new Action<Proyecto_Persona>(this.detach_Proyecto_Personas));
			this._Retroaliimentacion_Proyectos = new EntitySet<Retroaliimentacion_Proyecto>(new Action<Retroaliimentacion_Proyecto>(this.attach_Retroaliimentacion_Proyectos), new Action<Retroaliimentacion_Proyecto>(this.detach_Retroaliimentacion_Proyectos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula_Proponiente", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Cedula_Proponiente
		{
			get
			{
				return this._Cedula_Proponiente;
			}
			set
			{
				if ((this._Cedula_Proponiente != value))
				{
					this.OnCedula_ProponienteChanging(value);
					this.SendPropertyChanging();
					this._Cedula_Proponiente = value;
					this.SendPropertyChanged("Cedula_Proponiente");
					this.OnCedula_ProponienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Propuesta", DbType="VarChar(1024) NOT NULL", CanBeNull=false)]
		public string Propuesta
		{
			get
			{
				return this._Propuesta;
			}
			set
			{
				if ((this._Propuesta != value))
				{
					this.OnPropuestaChanging(value);
					this.SendPropertyChanging();
					this._Propuesta = value;
					this.SendPropertyChanged("Propuesta");
					this.OnPropuestaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recursos", DbType="VarChar(1024) NOT NULL", CanBeNull=false)]
		public string Recursos
		{
			get
			{
				return this._Recursos;
			}
			set
			{
				if ((this._Recursos != value))
				{
					this.OnRecursosChanging(value);
					this.SendPropertyChanging();
					this._Recursos = value;
					this.SendPropertyChanged("Recursos");
					this.OnRecursosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provincia", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Provincia
		{
			get
			{
				return this._Provincia;
			}
			set
			{
				if ((this._Provincia != value))
				{
					this.OnProvinciaChanging(value);
					this.SendPropertyChanging();
					this._Provincia = value;
					this.SendPropertyChanged("Provincia");
					this.OnProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Canton", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Canton
		{
			get
			{
				return this._Canton;
			}
			set
			{
				if ((this._Canton != value))
				{
					this.OnCantonChanging(value);
					this.SendPropertyChanging();
					this._Canton = value;
					this.SendPropertyChanged("Canton");
					this.OnCantonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromedioEvaluacion", DbType="SmallInt")]
		public System.Nullable<short> PromedioEvaluacion
		{
			get
			{
				return this._PromedioEvaluacion;
			}
			set
			{
				if ((this._PromedioEvaluacion != value))
				{
					this.OnPromedioEvaluacionChanging(value);
					this.SendPropertyChanging();
					this._PromedioEvaluacion = value;
					this.SendPropertyChanged("PromedioEvaluacion");
					this.OnPromedioEvaluacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadEvaluacionesUsarios", DbType="Int")]
		public System.Nullable<int> CantidadEvaluacionesUsarios
		{
			get
			{
				return this._CantidadEvaluacionesUsarios;
			}
			set
			{
				if ((this._CantidadEvaluacionesUsarios != value))
				{
					this.OnCantidadEvaluacionesUsariosChanging(value);
					this.SendPropertyChanging();
					this._CantidadEvaluacionesUsarios = value;
					this.SendPropertyChanged("CantidadEvaluacionesUsarios");
					this.OnCantidadEvaluacionesUsariosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this.OnFechaInicioChanging(value);
					this.SendPropertyChanging();
					this._FechaInicio = value;
					this.SendPropertyChanged("FechaInicio");
					this.OnFechaInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFinal", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaFinal
		{
			get
			{
				return this._FechaFinal;
			}
			set
			{
				if ((this._FechaFinal != value))
				{
					this.OnFechaFinalChanging(value);
					this.SendPropertyChanging();
					this._FechaFinal = value;
					this.SendPropertyChanged("FechaFinal");
					this.OnFechaFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(99)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlImagen", DbType="VarChar(256)")]
		public string urlImagen
		{
			get
			{
				return this._urlImagen;
			}
			set
			{
				if ((this._urlImagen != value))
				{
					this.OnurlImagenChanging(value);
					this.SendPropertyChanging();
					this._urlImagen = value;
					this.SendPropertyChanged("urlImagen");
					this.OnurlImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proyecto_Proyecto_Imagene", Storage="_Proyecto_Imagenes", ThisKey="Id", OtherKey="Id_Proyecto")]
		public EntitySet<Proyecto_Imagene> Proyecto_Imagenes
		{
			get
			{
				return this._Proyecto_Imagenes;
			}
			set
			{
				this._Proyecto_Imagenes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proyecto_Proyecto_Persona", Storage="_Proyecto_Personas", ThisKey="Id", OtherKey="IdProyecto")]
		public EntitySet<Proyecto_Persona> Proyecto_Personas
		{
			get
			{
				return this._Proyecto_Personas;
			}
			set
			{
				this._Proyecto_Personas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proyecto_Retroaliimentacion_Proyecto", Storage="_Retroaliimentacion_Proyectos", ThisKey="Id", OtherKey="Id_Proyecto")]
		public EntitySet<Retroaliimentacion_Proyecto> Retroaliimentacion_Proyectos
		{
			get
			{
				return this._Retroaliimentacion_Proyectos;
			}
			set
			{
				this._Retroaliimentacion_Proyectos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Proyecto_Imagenes(Proyecto_Imagene entity)
		{
			this.SendPropertyChanging();
			entity.Proyecto = this;
		}
		
		private void detach_Proyecto_Imagenes(Proyecto_Imagene entity)
		{
			this.SendPropertyChanging();
			entity.Proyecto = null;
		}
		
		private void attach_Proyecto_Personas(Proyecto_Persona entity)
		{
			this.SendPropertyChanging();
			entity.Proyecto = this;
		}
		
		private void detach_Proyecto_Personas(Proyecto_Persona entity)
		{
			this.SendPropertyChanging();
			entity.Proyecto = null;
		}
		
		private void attach_Retroaliimentacion_Proyectos(Retroaliimentacion_Proyecto entity)
		{
			this.SendPropertyChanging();
			entity.Proyecto = this;
		}
		
		private void detach_Retroaliimentacion_Proyectos(Retroaliimentacion_Proyecto entity)
		{
			this.SendPropertyChanging();
			entity.Proyecto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proyecto_Imagenes")]
	public partial class Proyecto_Imagene : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.Guid _Id_Proyecto;
		
		private string _urlImagen;
		
		private EntityRef<Proyecto> _Proyecto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnId_ProyectoChanging(System.Guid value);
    partial void OnId_ProyectoChanged();
    partial void OnurlImagenChanging(string value);
    partial void OnurlImagenChanged();
    #endregion
		
		public Proyecto_Imagene()
		{
			this._Proyecto = default(EntityRef<Proyecto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Proyecto", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Id_Proyecto
		{
			get
			{
				return this._Id_Proyecto;
			}
			set
			{
				if ((this._Id_Proyecto != value))
				{
					if (this._Proyecto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_ProyectoChanging(value);
					this.SendPropertyChanging();
					this._Id_Proyecto = value;
					this.SendPropertyChanged("Id_Proyecto");
					this.OnId_ProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlImagen", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string urlImagen
		{
			get
			{
				return this._urlImagen;
			}
			set
			{
				if ((this._urlImagen != value))
				{
					this.OnurlImagenChanging(value);
					this.SendPropertyChanging();
					this._urlImagen = value;
					this.SendPropertyChanged("urlImagen");
					this.OnurlImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proyecto_Proyecto_Imagene", Storage="_Proyecto", ThisKey="Id_Proyecto", OtherKey="Id", IsForeignKey=true)]
		public Proyecto Proyecto
		{
			get
			{
				return this._Proyecto.Entity;
			}
			set
			{
				Proyecto previousValue = this._Proyecto.Entity;
				if (((previousValue != value) 
							|| (this._Proyecto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proyecto.Entity = null;
						previousValue.Proyecto_Imagenes.Remove(this);
					}
					this._Proyecto.Entity = value;
					if ((value != null))
					{
						value.Proyecto_Imagenes.Add(this);
						this._Id_Proyecto = value.Id;
					}
					else
					{
						this._Id_Proyecto = default(System.Guid);
					}
					this.SendPropertyChanged("Proyecto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proyecto_Personas")]
	public partial class Proyecto_Persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _IdPersona;
		
		private System.Guid _IdProyecto;
		
		private string _Recursos;
		
		private string _Motivo;
		
		private EntityRef<Persona> _Persona;
		
		private EntityRef<Proyecto> _Proyecto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPersonaChanging(System.Guid value);
    partial void OnIdPersonaChanged();
    partial void OnIdProyectoChanging(System.Guid value);
    partial void OnIdProyectoChanged();
    partial void OnRecursosChanging(string value);
    partial void OnRecursosChanged();
    partial void OnMotivoChanging(string value);
    partial void OnMotivoChanged();
    #endregion
		
		public Proyecto_Persona()
		{
			this._Persona = default(EntityRef<Persona>);
			this._Proyecto = default(EntityRef<Proyecto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersona", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid IdPersona
		{
			get
			{
				return this._IdPersona;
			}
			set
			{
				if ((this._IdPersona != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPersonaChanging(value);
					this.SendPropertyChanging();
					this._IdPersona = value;
					this.SendPropertyChanged("IdPersona");
					this.OnIdPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProyecto", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid IdProyecto
		{
			get
			{
				return this._IdProyecto;
			}
			set
			{
				if ((this._IdProyecto != value))
				{
					if (this._Proyecto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdProyectoChanging(value);
					this.SendPropertyChanging();
					this._IdProyecto = value;
					this.SendPropertyChanged("IdProyecto");
					this.OnIdProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recursos", DbType="VarChar(1024) NOT NULL", CanBeNull=false)]
		public string Recursos
		{
			get
			{
				return this._Recursos;
			}
			set
			{
				if ((this._Recursos != value))
				{
					this.OnRecursosChanging(value);
					this.SendPropertyChanging();
					this._Recursos = value;
					this.SendPropertyChanged("Recursos");
					this.OnRecursosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motivo", DbType="VarChar(1024) NOT NULL", CanBeNull=false)]
		public string Motivo
		{
			get
			{
				return this._Motivo;
			}
			set
			{
				if ((this._Motivo != value))
				{
					this.OnMotivoChanging(value);
					this.SendPropertyChanging();
					this._Motivo = value;
					this.SendPropertyChanged("Motivo");
					this.OnMotivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Proyecto_Persona", Storage="_Persona", ThisKey="IdPersona", OtherKey="Id", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Proyecto_Personas.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Proyecto_Personas.Add(this);
						this._IdPersona = value.Id;
					}
					else
					{
						this._IdPersona = default(System.Guid);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proyecto_Proyecto_Persona", Storage="_Proyecto", ThisKey="IdProyecto", OtherKey="Id", IsForeignKey=true)]
		public Proyecto Proyecto
		{
			get
			{
				return this._Proyecto.Entity;
			}
			set
			{
				Proyecto previousValue = this._Proyecto.Entity;
				if (((previousValue != value) 
							|| (this._Proyecto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proyecto.Entity = null;
						previousValue.Proyecto_Personas.Remove(this);
					}
					this._Proyecto.Entity = value;
					if ((value != null))
					{
						value.Proyecto_Personas.Add(this);
						this._IdProyecto = value.Id;
					}
					else
					{
						this._IdProyecto = default(System.Guid);
					}
					this.SendPropertyChanged("Proyecto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Retroaliimentacion_Proyecto")]
	public partial class Retroaliimentacion_Proyecto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _Id_Proyecto;
		
		private string _Url_Archivo;
		
		private string _Comentario;
		
		private EntityRef<Proyecto> _Proyecto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnId_ProyectoChanging(System.Guid value);
    partial void OnId_ProyectoChanged();
    partial void OnUrl_ArchivoChanging(string value);
    partial void OnUrl_ArchivoChanged();
    partial void OnComentarioChanging(string value);
    partial void OnComentarioChanged();
    #endregion
		
		public Retroaliimentacion_Proyecto()
		{
			this._Proyecto = default(EntityRef<Proyecto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Proyecto", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Id_Proyecto
		{
			get
			{
				return this._Id_Proyecto;
			}
			set
			{
				if ((this._Id_Proyecto != value))
				{
					if (this._Proyecto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_ProyectoChanging(value);
					this.SendPropertyChanging();
					this._Id_Proyecto = value;
					this.SendPropertyChanged("Id_Proyecto");
					this.OnId_ProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url_Archivo", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string Url_Archivo
		{
			get
			{
				return this._Url_Archivo;
			}
			set
			{
				if ((this._Url_Archivo != value))
				{
					this.OnUrl_ArchivoChanging(value);
					this.SendPropertyChanging();
					this._Url_Archivo = value;
					this.SendPropertyChanged("Url_Archivo");
					this.OnUrl_ArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this.OnComentarioChanging(value);
					this.SendPropertyChanging();
					this._Comentario = value;
					this.SendPropertyChanged("Comentario");
					this.OnComentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proyecto_Retroaliimentacion_Proyecto", Storage="_Proyecto", ThisKey="Id_Proyecto", OtherKey="Id", IsForeignKey=true)]
		public Proyecto Proyecto
		{
			get
			{
				return this._Proyecto.Entity;
			}
			set
			{
				Proyecto previousValue = this._Proyecto.Entity;
				if (((previousValue != value) 
							|| (this._Proyecto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proyecto.Entity = null;
						previousValue.Retroaliimentacion_Proyectos.Remove(this);
					}
					this._Proyecto.Entity = value;
					if ((value != null))
					{
						value.Retroaliimentacion_Proyectos.Add(this);
						this._Id_Proyecto = value.Id;
					}
					else
					{
						this._Id_Proyecto = default(System.Guid);
					}
					this.SendPropertyChanged("Proyecto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
